# Generated by Django 5.0.2 on 2024-03-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('loan_application_date', models.DateField(blank=True, null=True)),
                ('purpose_of_loan', models.CharField(blank=True, max_length=255)),
                ('address_location', models.CharField(blank=True, max_length=255)),
                ('business_financed', models.CharField(blank=True, max_length=255)),
                ('group_name', models.CharField(blank=True, max_length=100)),
                ('reason_for_default_summarised', models.CharField(blank=True, max_length=255)),
                ('detailed_reason_for_default', models.TextField(blank=True)),
            ],
        ),
    ]
