# Generated by Django 5.0.2 on 2024-03-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client_account_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_From_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ACCTNUM', models.CharField(max_length=50, unique=True)),
                ('ACCT_NAME', models.CharField(max_length=100)),
                ('loan_application_date', models.DateField(blank=True)),
                ('address_location', models.CharField(blank=True, max_length=255)),
                ('purpose_of_loan', models.CharField(blank=True, max_length=255)),
                ('business_financed', models.CharField(blank=True, max_length=255)),
                ('group_name', models.CharField(blank=True, max_length=100)),
                ('reason_for_default_summarised', models.CharField(blank=True, max_length=255)),
                ('detailed_reason_for_default', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='client_account',
            old_name='account_number',
            new_name='ACCTNUM',
        ),
        migrations.RenameField(
            model_name='client_account',
            old_name='account_manager_user_id',
            new_name='ACCT_MGR_USER_ID',
        ),
        migrations.RenameField(
            model_name='client_account',
            old_name='account_name',
            new_name='ACCT_NAME',
        ),
        migrations.RenameField(
            model_name='client_account',
            old_name='age',
            new_name='AGE',
        ),
        migrations.RenameField(
            model_name='client_account',
            old_name='age_category',
            new_name='AGE_CATEGORY',
        ),
        migrations.RenameField(
            model_name='client_account',
            old_name='amount_claimed',
            new_name='AMOUNT_CLAIMED',
        ),
        migrations.RenameField(
            model_name='client_account',
            old_name='claim_status',
            new_name='CIF_ID',
        ),
        migrations.RenameField(
            model_name='client_account',
            old_name='contact',
            new_name='CLAIM_STATUS',
        ),
        migrations.RenameField(
            model_name='client_account',
            old_name='gender',
            new_name='CLASSIFICATION',
        ),
        migrations.RenameField(
            model_name='client_account',
            old_name='loan_cycle',
            new_name='COMBINED_CIF',
        ),
        migrations.RenameField(
            model_name='client_account',
            old_name='loan_term',
            new_name='CONTACT',
        ),
        migrations.RenameField(
            model_name='client_account',
            old_name='debt_arrears_start_date',
            new_name='DATE_ARREARS_START',
        ),
        migrations.RenameField(
            model_name='client_account',
            old_name='disbursed_amount',
            new_name='DIS_AMT',
        ),
        migrations.RenameField(
            model_name='client_account',
            old_name='disbursement_date',
            new_name='DIS_SHDL_DATE',
        ),
        migrations.RenameField(
            model_name='client_account',
            old_name='loan_balance',
            new_name='FLOW_AMT',
        ),
        migrations.RenameField(
            model_name='client_account',
            old_name='mode_of_engagement',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='client_account',
            old_name='principal_balance',
            new_name='PRINCIPLE_BALANCE',
        ),
        migrations.RemoveField(
            model_name='client_account',
            name='address_location',
        ),
        migrations.RemoveField(
            model_name='client_account',
            name='business_financed',
        ),
        migrations.RemoveField(
            model_name='client_account',
            name='days_in_arrears',
        ),
        migrations.RemoveField(
            model_name='client_account',
            name='detailed_reason_for_default',
        ),
        migrations.RemoveField(
            model_name='client_account',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='client_account',
            name='loan_application_date',
        ),
        migrations.RemoveField(
            model_name='client_account',
            name='purpose_of_loan',
        ),
        migrations.RemoveField(
            model_name='client_account',
            name='reason_for_default_summarised',
        ),
        migrations.AddField(
            model_name='client_account',
            name='LCYBALANCE',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='client_account',
            name='LOAN_CYCLE',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client_account',
            name='MAT_DATE',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='client_account',
            name='MODE_OF_ENGAGEMENT',
            field=models.CharField(default='DIRECT', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client_account',
            name='SCHEME_NAME',
            field=models.CharField(default='YOUNG AFRICA WORKS', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client_account',
            name='SCHM_CODE',
            field=models.CharField(default='LA508', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client_account',
            name='TERM',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
