# Generated by Django 5.0.2 on 2024-03-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_client_from_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_account',
            name='ARREARSDAYS',
            field=models.CharField(default=180, max_length=50),
            preserve_default=False,
        ),
    ]
