# Generated by Django 5.0.2 on 2024-03-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_client_account_arrearsdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_account',
            name='SOL_ID',
            field=models.CharField(max_length=50),
        ),
    ]
