# Generated by Django 5.0.3 on 2024-03-20 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0006_alter_client_account_sol_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client_account',
            options={'permissions': [('view_client_account_details', 'Can view client account details'), ('edit_client_account_info', 'Can edit client account information')]},
        ),
        migrations.AddField(
            model_name='client_account',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.CreateModel(
            name='Client_Account_Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client_account')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.AddField(
            model_name='client_account',
            name='groups',
            field=models.ManyToManyField(related_name='client_accounts', through='core.Client_Account_Groups', to='auth.group'),
        ),
        migrations.CreateModel(
            name='Client_Account_User_Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client_account')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
            ],
        ),
        migrations.AddField(
            model_name='client_account',
            name='user_permissions',
            field=models.ManyToManyField(related_name='client_accounts', through='core.Client_Account_User_Permissions', to='auth.permission'),
        ),
    ]
