# Generated by Django 5.0.3 on 2024-03-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_client_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_account',
            name='CIF_ID',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='client_account',
            name='COMBINED_CIF',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
