# Generated by Django 5.0.3 on 2024-03-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_client_account_cif_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_account',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='client_account_user_permissions',
            name='client_account',
        ),
        migrations.RemoveField(
            model_name='client_account_user_permissions',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='client_account',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='relatedmodel',
            name='client_account',
        ),
        migrations.AlterModelOptions(
            name='client_account',
            options={},
        ),
        migrations.RenameField(
            model_name='client_account',
            old_name='GENDER',
            new_name='Gender',
        ),
        migrations.RemoveField(
            model_name='client_account',
            name='is_superuser',
        ),
        migrations.AddField(
            model_name='client_account',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client_account',
            name='ACCTNUM',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='client_account',
            name='CIF_ID',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client_account',
            name='COMBINED_CIF',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Client_Account_Groups',
        ),
        migrations.DeleteModel(
            name='Client_Account_User_Permissions',
        ),
        migrations.DeleteModel(
            name='RelatedModel',
        ),
    ]
