# Generated by Django 5.0.3 on 2024-03-20 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_client_account_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_account',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='client_account_user_permissions',
            name='client_account',
        ),
        migrations.RemoveField(
            model_name='client_account_user_permissions',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='client_account',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='relatedmodel',
            name='client_account',
        ),
        migrations.AlterModelOptions(
            name='client_account',
            options={},
        ),
        migrations.RenameField(
            model_name='client_account',
            old_name='reason_for_default_summarised',
            new_name='reason_for_default',
        ),
        migrations.RemoveField(
            model_name='client_account',
            name='detailed_reason_for_default',
        ),
        migrations.RemoveField(
            model_name='client_account',
            name='is_superuser',
        ),
        migrations.DeleteModel(
            name='Client_Account_Groups',
        ),
        migrations.DeleteModel(
            name='Client_Account_User_Permissions',
        ),
        migrations.DeleteModel(
            name='RelatedModel',
        ),
    ]
