# Generated by Django 5.0.3 on 2024-03-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_client_account_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_account',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client_account',
            name='ACCTNUM',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='client_account',
            name='CIF_ID',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client_account',
            name='COMBINED_CIF',
            field=models.CharField(max_length=50),
        ),
    ]
